name: flutter_event_calendar_french
description: Add French and Gregorian and Jalali Event calendar for flutter with options for change style
version: 1.0.0
homepage: https://github.com/mariewebdesign/flutter_event_calendar_french

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  shamsi_date: ^0.15.0
  scoped_model: ^2.0.0
  flutter:
    sdk: flutter
  collection: ^1.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
